Fix use-proxy, bad port -> string conversion
Calling string() on an int results in a rune, not the expected string.
That caused an error like:

Error: failed to query allocation API: failed to proxy get kubecost. err: the server is currently unable to handle the request (get services kubecost-cost-analyzer:⎂); data: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"no endpoints available for service \"kubecost-cost-analyzer:⎂\"","reason":"ServiceUnavailable","code":503}

Note the port after "kubecost-cost-analyzer:"

After this commit, use-proxy works correctly.